url: "https://fricklerhandwerk.github.io"
github-user: fricklerhandwerk
github-repo: smbc
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
    values:
      layout: page
collections:
  comics:
    output: true
    layout: default
    permalink: /:name
exclude:
  - script
  - default.nix
plugins:
  - jekyll-sitemap
