github-user: fricklerhandwerk
github-repo: smbc
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
    values:
      layout: page
collections:
  comics:
    output: true
    layout: default
exclude:
  - script
  - default.nix
